language: python
matrix:
  include:
  - python: 2.7
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.8
  - python: "3.8-dev"
  - python: "nightly"
  
  include:
    - name: "Python 3.8 on macOS"
      os: osx
      language: shell
      python: 3.8
      
  include:
    - name: "Python 3.8.2 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.2
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
script: python minimal_test.py
